### ISSUE TITLE
Wb image showing invalid json in  wb link

### ISSUE THREAD

**Issue by nisha509** [Virtusa-Systems-LLC/whiteboard#15]
https://ecswb.talentacad.com/?whiteboardid=SITRIPROREA-Q1&accesstoken=vss
![image](https://user-images.githubusercontent.com/77163718/198829241-d7c1ce95-2477-428d-8c67-452f1fef5434.png)

**Comment by nisha509** [comment]
https://admin.virtusasystems.com/question_sets/735/view_question/1
https://student.talentacad.com/quiz/attempt/exam/949?c=TWluaSBHZW9tZXRyeSAvICBNaW5pIEdlb21ldHJ5OiBTaW1pbGFyIHRyaWFuZ2xlcyAgLyAgU2ltaWxhciBUcmlhbmdsZXMgYW5kIFByb3BvcnRpb25hbCBSZWFzb25pbmcgKFdCKQ==&cn=R2VvbWV0cnkgTGV2ZWwgMg--

**Comment by somiya12** [comment]
![image](https://user-images.githubusercontent.com/91362823/198847150-633e2c8f-bfb7-47d4-a89d-2e14456fc451.png)
After clicking on reset
 It shows
 invalid json

**Comment by somiya12** [comment]
![image](https://user-images.githubusercontent.com/91362823/198847636-7c0c8ca3-546e-4d18-a46c-bc5a675d36eb.png)
after getting the url and running reset then 
wb_json_data shows blank that's why it is not showing data on whiteboard and showing invalid json

**Comment by baibhav007** [comment]
### It is there in the database too
![image](https://user-images.githubusercontent.com/53268623/199253206-74299373-5b0c-4442-81a0-7bc4e755709e.png)

**Comment by baibhav007** [comment]
### Even after deleting the entry (I have put the data back now) but it's still showing data in the front end
![image](https://user-images.githubusercontent.com/53268623/199255231-f17e6dc1-937c-4a33-8804-8935c37cfa89.png)

**Comment by baibhav007** [comment]
### It is not updating data with new data & there is a cache problem as well
![image](https://user-images.githubusercontent.com/53268623/199256345-66089114-6826-48f6-bc3f-d89bd6f83a8a.png)

**Comment by neetubabli** [comment]
How can we fix it?
need solution.

**Comment by nisha509** [comment]
The problem in ecb wb is when we want to reset it showing invalid json
![image](https://user-images.githubusercontent.com/77163718/199258387-4a479459-07b2-48a6-981e-ff24488631f0.png)

**Comment by gaurav00012** [comment]
Resolved invalida json response by identifying that we don't have to split whitborad id which we are getting from param

![image](https://user-images.githubusercontent.com/22203154/200613628-291460e3-3baf-4daa-94dc-a2caab13be08.png)

**Comment by nisha509** [comment]
but still i m bot able to reset json it showing same message 
![image](https://user-images.githubusercontent.com/77163718/200614073-f78319b6-f949-498d-ab61-28ca0e931dad.png)
https://ecswb.talentacad.com/?whiteboardid=AMC12A2002JAN-Q1&accesstoken=vss

**Comment by gaurav00012** [comment]
ok i let me check and resolve this

**Comment by gaurav00012** [comment]
I resolved issue in local and pushed code in master . Please check on production and let me know if getting any error
![image](https://user-images.githubusercontent.com/22203154/200644782-0d24cc40-821d-4b70-a60f-95f76046a2af.png)
![image](https://user-images.githubusercontent.com/22203154/200644836-cc759bb7-7b6f-41c1-8e97-76eec668b47c.png)
![image](https://user-images.githubusercontent.com/22203154/200644874-1a23bc19-af05-4f39-9317-7051316e6089.png)
![image](https://user-images.githubusercontent.com/22203154/200644886-aec64232-6076-48da-839b-5c7efc7d28d7.png)

**Comment by nisha509** [comment]
Please check this links I m getting Same error
https://ecswb.talentacad.com/?whiteboardid=AMC12A2002JAN-Q1&accesstoken=vss

**Comment by nisha509** [comment]
Where is git commit code? @baibhav007 can you explain to Gaurav how to commit code

**Comment by gaurav00012** [comment]
Understanding the flow of whiteboard 

Getting json response from 
http://localhost:8080/api/loadwhiteboard?wid=AMC82008-Q2&at=vss

![image](https://user-images.githubusercontent.com/22203154/200883212-dbc95bf8-2bb4-4c73-9c78-0412187ec0f7.png)
